apiVersion: apps/v1
kind: Deployment

metadata:
  name: netflix-deployment

spec:
  replicas: 2

  selector:
    matchLabels:
      app: netflix

  template:
    metadata:
      labels:
        app: netflix

    spec:
      # Disable automatic mounting of the service account token
      automountServiceAccountToken: false

      containers:
        - name: netflix

          # Use a specific image tag instead of latest
          image: chaitali1513/netflix-clone:IMAGE_TAG

          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 80

          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
              ephemeral-storage: "1Gi"

            limits:
              cpu: "500m"
              memory: "512Mi"
              ephemeral-storage: "2Gi"